#version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    container_name: rust_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://appuser:password@db:5432/appdb
    ports:
      - "8080:8080"
volumes:
  postgres_data: